/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientUser;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author CARLOS
 */
public class PerfilUser extends javax.swing.JFrame {
    String email_parameter;
    /**
     * Creates new form PerfilUser
     */
    public PerfilUser(String email_parameter) {
        initComponents();
        this.setLocationRelativeTo(null);
        PanelPrincipal.setBackground(new Color(0,0,0,150));
        setVisible(true);
        this.email_parameter = email_parameter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        Noticias = new javax.swing.JButton();
        Promos = new javax.swing.JButton();
        Colab = new javax.swing.JButton();
        Client = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bienvenido, que empieze la magia...!! ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CLIENTE/Prosegur2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 310, 130));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1190, 700));

        Noticias.setText("NOTICIAS");
        Noticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoticiasActionPerformed(evt);
            }
        });
        getContentPane().add(Noticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        Promos.setText("PROMOS");
        Promos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromosActionPerformed(evt);
            }
        });
        getContentPane().add(Promos, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, -1, -1));

        Colab.setText("COLABORADORES");
        Colab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColabActionPerformed(evt);
            }
        });
        getContentPane().add(Colab, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        Client.setText("CLIENTES");
        Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientActionPerformed(evt);
            }
        });
        getContentPane().add(Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, -1, -1));

        btnCerrarSesion.setText("CERRAR SESION");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CLIENTE/Prosegur.jpg"))); // NOI18N
        jLabel1.setText("CERRAR SESION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1242, 912));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoticiasActionPerformed
        
        Noticias p2 = new Noticias();
        p2.setSize(1120,530);
        p2.setLocation(5,5);
       
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p2,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
    }//GEN-LAST:event_NoticiasActionPerformed

    private void PromosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromosActionPerformed
        
        Promos p3 = new Promos();
        p3.setSize(1120,530);
        p3.setLocation(5,5);
       
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p3,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
        
    }//GEN-LAST:event_PromosActionPerformed

    private void ColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColabActionPerformed
        
        ListaTrabajadr p4 = new ListaTrabajadr(email_parameter);
        p4.setSize(1120,530);
        p4.setLocation(5,5);
       
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p4,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
        
    }//GEN-LAST:event_ColabActionPerformed

    private void ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientActionPerformed
        
        ListaClientes p5 = new ListaClientes();
        p5.setSize(1120,530);
        p5.setLocation(5,5);
       
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p5,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
        
    }//GEN-LAST:event_ClientActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        Welcom W = new Welcom();
        dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Client;
    private javax.swing.JButton Colab;
    private javax.swing.JButton Noticias;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton Promos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
