/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ClientUser.PerfilUser;
import javax.swing.JOptionPane;
import mktApp.bussines.MainManager;
import mktApp.entity.Potential;
import mktApp.utility.Clean;

/**
 *
 * @author CARLOS
 */
public class CONTACTS extends javax.swing.JPanel {
    Potential potential1 = new Potential();
    /**
     * Creates new form CONTACTS
     */
    public CONTACTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtInteres = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtemail = new javax.swing.JTextField();
        jtxtEmail_adviser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnEnvio = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTACTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ARGO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jr. Las Begonias 480 ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jesús Maria, Lima");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("fisi.2018@unmsm.edu.pe");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telf: 992-146-167");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        add(jtxtInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 410, 110));
        add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 410, 30));
        add(jtxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 410, 30));
        add(jtxtEmail_adviser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 410, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-mail");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contacto (Correo)");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 40));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Asunto");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        btnEnvio.setText("ENVIAR");
        btnEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvioActionPerformed(evt);
            }
        });
        add(btnEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/967d6b649c2d7a1dc2c29622dd17e17b.jpg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 440, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvioActionPerformed
        // TODO add your handling code here:
        Potential potential = new Potential();
        potential.setFirst_name(jtxtNombre.getText());
        potential.setEmail(jtxtemail.getText());
        potential.setEmail_adviser(jtxtEmail_adviser.getText());
        potential.setInterest(jtxtInteres.getText());
        if (potential.getFirst_name().trim().equals("") == true) {
                JOptionPane.showMessageDialog(this, "El Nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (potential.getEmail().trim().equals("") == true) {
                    JOptionPane.showMessageDialog(this, "El Correo no puede estar vacia", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (potential.getEmail_adviser().trim().equals("") == true) {
                    JOptionPane.showMessageDialog(this, "El Correo de su contacto no puede estar vacia", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (potential.getInterest().trim().equals("") == true) {
                    JOptionPane.showMessageDialog(this, "El asunto no puede estar vacia", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            boolean status = MainManager.getPotentialUserManager().signUpPotential(potential);
                if (status == true) {
                    JOptionPane.showMessageDialog(this, "¡Usuario registrado", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                    int response = JOptionPane.showConfirmDialog(this, "¿Desea guardar los cambios efectuados?", "Guardar", JOptionPane.YES_NO_OPTION);
                    if (response == JOptionPane.YES_OPTION) {
                        boolean status_response = MainManager.getDatabaseManager().guardarCambios();
                        /*PerfilUser pu = new PerfilUser(potential.getEmail());
                        pu.setVisible(true);*/
                        Clean C = new Clean();
                    } else if (response == JOptionPane.NO_OPTION) {
                        Clean C = new Clean();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar al Usuario, verifique que no esté ya registrado.", "Error", JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_btnEnvioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtxtEmail_adviser;
    private javax.swing.JTextField jtxtInteres;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtemail;
    // End of variables declaration//GEN-END:variables
}
