/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Promoción.Contact;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author CARLOS
 */
public class Interfaz extends javax.swing.JFrame {
    String adviser_email_parameter;
    /**
     * Creates new form Interfaz
     */
    public Interfaz(String adviser_email) {
        initComponents();
        transparenciaBotones();
        this.setLocationRelativeTo(null);
        setVisible(true);
        PanelPrincipal.setBackground(new Color(0,0,0,150));
        adviser_email_parameter = adviser_email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void transparenciaBotones(){
    
        bt1.setOpaque(false);
        bt1.setContentAreaFilled(false); 
        bt1.setBorderPainted(false);
        
        bt2.setOpaque(false);
        bt2.setContentAreaFilled(false); 
        bt2.setBorderPainted(false);
        
        bt3.setOpaque(false);
        bt3.setContentAreaFilled(false); 
        bt3.setBorderPainted(false);
        
        bt4.setOpaque(false);
        bt4.setContentAreaFilled(false); 
        bt4.setBorderPainted(false);
        
        exit.setOpaque(false);
        exit.setContentAreaFilled(false); 
        exit.setBorderPainted(false);
    
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JPanel();
        btnAdquirir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, -1, -1));

        bt1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home1.png"))); // NOI18N
        bt1.setBorder(null);
        bt1.setBorderPainted(false);
        bt1.setContentAreaFilled(false);
        bt1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.png"))); // NOI18N
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 90, 30));

        bt2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about1.png"))); // NOI18N
        bt2.setBorder(null);
        bt2.setBorderPainted(false);
        bt2.setContentAreaFilled(false);
        bt2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about2.png"))); // NOI18N
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 90, 30));

        bt3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clients1.png"))); // NOI18N
        bt3.setBorder(null);
        bt3.setBorderPainted(false);
        bt3.setContentAreaFilled(false);
        bt3.setPreferredSize(new java.awt.Dimension(126, 45));
        bt3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clients2.png"))); // NOI18N
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 100, 30));

        bt4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contacts1.png"))); // NOI18N
        bt4.setBorder(null);
        bt4.setBorderPainted(false);
        bt4.setContentAreaFilled(false);
        bt4.setPreferredSize(new java.awt.Dimension(156, 45));
        bt4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contacts2.png"))); // NOI18N
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 90, 130, 30));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 1120, 530));

        btnAdquirir.setText("ARQUIRIR UN PRODUCTO");
        btnAdquirir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdquirirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdquirir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Interfaz.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        ABOUT p2 = new ABOUT();
        p2.setSize(1120,530);
        p2.setLocation(5,5);
       
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p2,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
            
        HOME p1 = new HOME();
        p1.setSize(1120,530);
        p1.setLocation(5,5);
       
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p1,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        CLIENTS p3 = new CLIENTS();
        p3.setSize(1120,530);
        p3.setLocation(5,5);
       
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p3,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        
        CONTACTS p4 = new CONTACTS();
        p4.setSize(1120,530);
        p4.setLocation(5,5);
       
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p4,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
    }//GEN-LAST:event_bt4ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_exitActionPerformed

    private void btnAdquirirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdquirirActionPerformed
        // TODO add your handling code here:
        Contact c = new Contact(adviser_email_parameter);
        
    }//GEN-LAST:event_btnAdquirirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton btnAdquirir;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
